name: "development-react-template"

volumes:
  home-data:
  node-modules-data:
include:
  - ../services/docker-compose.yml

services:
  app:
    ports:
      - 5173:5173
    build:
      context: ../../
      dockerfile: docker/dev/dockerfile
    volumes:
      - ../../:/app
      - home-data:/home/node
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.zshrc:/home/node/.zshrc
      - ~/.config/gh/hosts.yml:/home/node/.config/gh/hosts.yml
    deploy:
      resources:
        limits:
          memory: 4g
