name: build-push
run-name: Build & push - ${{ github.run_number }}
on:
  workflow_run:
    workflows: ["tests"]
    branches: ["main", "dev"]
    types:
      - completed

jobs:
  build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./dockerfile
          target: production
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apps:${{ github.event.repository.name }}-${{ github.ref_name }}-latest
          build-args: |
            VITE_BUILD_MODE=${{ github.ref_name == 'master' && 'prod' || 'dev' }}
