name: integration-tests
run-name: Integration Tests - ${{ github.run_number }}

on:
  workflow_run:
    workflows: ["unit-tests"]
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests and healthChecker
        run: docker compose -f ./docker/test/docker-compose.yml up --wait --wait-timeout 120 --build --remove-orphans

      - name: View logs on failure
        if: failure()
        run: docker compose -f ./docker/test/docker-compose.yml logs

      - name: Shutdown all services
        if: always()
        run: docker compose -f ./docker/test/docker-compose.yml down -v
