name: tests
run-name: Tests & health checker - ${{ github.run_number }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests and healthChecker
        run: docker compose up -f ./docker/test/docker-compose.yml --wait --wait-timeout 480

      - name: Shutdown all services
        if: always()
        run: docker compose -f ./docker/test/docker-compose.yml down

      - name: View logs on failure
        if: failure()
        run: docker compose -f ./docker/test/docker-compose.yml logs
